### ISSUE TITLE
Ex. 0.3.4

### ISSUE THREAD

**Issue by JonathanRamati** [isdsucph/isds2021#13]
Hi there
I'm a bit confused about how the loop should be made and how you add the partial sum into this loop?

**Comment by lassearpe** [comment]
Hey Jonathan

I was in doubt as well, and Joachim provided me with a good answer. If it is any help, you can find it under the "Closed"-section.

**Comment by JonathanRamati** [comment]
Hey Lasse
Thanks for the tip, it helped me too.
