### ISSUE TITLE
Ex 0.4.6

### ISSUE THREAD

**Issue by Konstantin-Babayan** [isdsucph/isds2021#20]
I am a little bit confused about a certain question in this exercise: "What is the date for the first and last observations?"

Do you want to know the exact date of the first and last observations overall? 
- The answer to this question is pretty obvious 18630101 and 18631231

Or do you want the date of the first and last observations from the df_sorted table?

All the best  
Konstantin

**Comment by joachimkrasmussen** [comment]
Hi,

Did you close this on purpose, or do you still need help with this?

Best,
Joachim

**Comment by Konstantin-Babayan** [comment]
I think I figured it out: you want  the date of the first and last observations from the df_sorted table. 

Correct?

**Comment by joachimkrasmussen** [comment]
Yes - that is, the date that is associated with the highest and the lowest temperature.

Best,
Joachim
