### ISSUE TITLE
Wrong assert statements?

### ISSUE THREAD

**Issue by johankll** [isdsucph/isds2021#25]
Hi, 

I just received assignment 0 in a "corrected" version which shows the hidden assert statements. I wonder what I have done wrong in the following two exercises?

**Ex. 0.1.3** _(i think it may be a mistake that the assert statement requires `answer_0031 == 5.3`, when 1.7+4 is quite obviously not 5.3)_
![image](https://user-images.githubusercontent.com/87449482/127692000-3cf1f451-4343-427d-b722-fd093bffa5ab.png)

**Ex. 0.3.1** _(i have tried applying my function to the lists in the assert statements and get the right results, so I don't understand what is wrong)_:
![image](https://user-images.githubusercontent.com/87449482/127691653-971ddb97-b941-44d6-99a6-ca7f53e51c55.png)

**Comment by joachimkrasmussen** [comment]
Hi Johan,

Regarding _Ex. 0.1.3_: It's clearly a typo in the assignment. As you say, you obviously got it right.

Regarding _Ex. 0.3.1_: The question asks you to return a _tuple_. What you return with your function is a _list_ (of tuples). Hence, there seems to be nothing wrong with the assert statement which looks for a tuple.

Best,
Joachim

**Comment by johankll** [comment]
Thanks!
