### ISSUE TITLE
Problem regarding time series data

### ISSUE THREAD

**Issue by lassearpe** [isdsucph/isds2021#28]
Hello

Anyone here able to tell my why my new date-column shows up as epoch and not the standard format? 

![image](https://user-images.githubusercontent.com/77959268/128041677-0eb3bc1e-997e-4411-99a9-4039864e4dc4.png)

Best, Lasse

**Comment by MatPiq** [comment]
Hi Lasse!
I would try to look at the steps you've taken before this snippet. To me It looks like you might already have changed the column "datetime" to a datetime object but without specifying the correct format? Let me know if it doesn't work out!

**Comment by lassearpe** [comment]
You are indeed correct. Just had to run the above columns again. Thanks!

Best, Lasse
