### ISSUE TITLE
Problem 0.3.2

### ISSUE THREAD

**Issue by Casper17-max** [isdsucph/isds2021#5]
![image](https://user-images.githubusercontent.com/86822716/125189471-8c9bd180-e238-11eb-9f0c-57bbcd084e5f.png)

Jeg forstår ikke hvad problemet er i 'in [21]:'

**Comment by joachimkrasmussen** [comment]
Hi Casper,

It seems that you are simply printing a function. Note that your function is taking a argument _y_. Try and print your function while also specifying the argument (like: print(my_fun(y))).

Best,
Joachim

**Comment by Casper17-max** [comment]
Thank you, that helped :-)

**Comment by johankll** [comment]
Hi Joachim, 

I have played a bit around with defining variables with and without 'print'. I seem to come to the conclusion that the print-function simply returns 'None'. Hence, the above code simply defines answer_032a=answer_032b=None. 

Is my observation correct, or am I missing something? (the below picture illustrates what i have "found")
![image](https://user-images.githubusercontent.com/87449482/126215943-83de2b1c-fbdb-4f93-9ab1-26bfe05debf6.png)

**Comment by joachimkrasmussen** [comment]
Hi Johan

My experience is that you should generally not define any variables the following way:
`y = print(2*x)`

Always do the following:
```
y = 2*x
print(y)
```

That is, don't generally create a new object from `print()`. In general, only use `print()` when you have a personal desire to understand what is going on with your code. Does that make sense?

Best,
Joachim

**Comment by johankll** [comment]
Hi Joachim, 

Thanks for the answer.

It makes perfect sense. It is exactly what i thought. 

/Johan
