### ISSUE TITLE
Inspection

### ISSUE THREAD

**Issue by Casper17-max** [isdsucph/isds2021#6]
![image](https://user-images.githubusercontent.com/86822716/125189757-fe284f80-e239-11eb-98c9-eab0d4853f29.png)

I think I copied this exact from the assignment, I don't know why 'dp' is not defined.

**Comment by joachimkrasmussen** [comment]
Hi Casper,

Did you remember first to run: _import pandas as pd_?

Best,
Joachim

**Comment by Casper17-max** [comment]
I tried to google what this new error mean, but none of the suggested solutions worked for me:
![image](https://user-images.githubusercontent.com/86822716/125750614-c161ee40-2075-40f6-be67-28a627c186a7.png)

**Comment by joachimkrasmussen** [comment]
Try and do the following:
Click: Kernel -> 'restart and clear output'

Then add the following to the top of the cell: _import numpy as np_

Then run this cell and only this cell. Does it work now?

**Note:** When you restart the kernel and clear the output, all your outputs will disappear, and you will have to run everything again to get your output. This should not be a problem if you have written your code properly!

/Joachim

**Comment by Casper17-max** [comment]
It worked, thank you
