### ISSUE TITLE
How to submit answers

### ISSUE THREAD

**Issue by johankll** [isdsucph/isds2021#9]
I am unsure as to how you want us to submit our answers. 
As an example: In problem 0.3.1, you have left the following cell:

![image](https://user-images.githubusercontent.com/87449482/125951891-6b263e2b-f5db-42ac-83a6-06bdd90121c3.png)

I realize that you want us to erase "raise NotImplementedError()" and write our code here... But do you also want us to fill in the answers on the first and second line?

**Comment by joachimkrasmussen** [comment]
Hi Johan,

No, not really. It's just in order to show you how the answer can be written up. You should erase the _raise NotImplementedError()_ and write your answer there in the same style as illustrated above (just without the _#_). Does that make sense?

Best,
Joachim

**Comment by johankll** [comment]
Hi Joachim, 

Yes, it makes sense. Thank you!
